### ISSUE TITLE
error during rosdep install 

### ISSUE THREAD

**Issue by prabanjanGITHUB** [Robotics010/carla_autoware_bridge#18]
pp@DESKTOP-TGAP0QJ:~/autoware$ rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/freeze.py", line 100, in run
    for line in freeze(**freeze_kwargs):
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/freeze.py", line 70, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/freeze.py", line 257, in from_dist
    req = dist.as_requirement()
  File "/home/pp/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2918, in as_requirement
    if isinstance(self.parsed_version, packaging.version.Version):
  File "/home/pp/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2734, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
occupancy_grid_map_outlier_filter: Cannot locate rosdep definition for [pcl_ros]
velodyne_monitor: Cannot locate rosdep definition for [diagnostic_updater]
lidar_centerpoint: Cannot locate rosdep definition for [pcl_ros]
costmap_generator: Cannot locate rosdep definition for [pcl_ros]
front_vehicle_velocity_estimator: Cannot locate rosdep definition for [pcl_ros]
grid_map_costmap_2d: Cannot locate rosdep definition for [nav2_costmap_2d]
lidar_apollo_segmentation_tvm: Cannot locate rosdep definition for [tvm_vendor]
steer_offset_estimator: Cannot locate rosdep definition for [diagnostic_updater]
fault_injection: Cannot locate rosdep definition for [diagnostic_updater]
trtexec_vendor: Cannot locate rosdep definition for [tensorrt_cmake_module]
dummy_diag_publisher: Cannot locate rosdep definition for [diagnostic_updater]
web_controller: Cannot locate rosdep definition for [rosbridge_server]
obstacle_collision_checker: Cannot locate rosdep definition for [pcl_ros]
system_error_monitor: Cannot locate rosdep definition for [rqt_robot_monitor]
vehicle_cmd_gate: Cannot locate rosdep definition for [diagnostic_updater]
radar_tracks_msgs_converter: Cannot locate rosdep definition for [radar_msgs]
grid_map_demos: Cannot locate rosdep definition for [octomap_msgs]
planning_error_monitor: Cannot locate rosdep definition for [diagnostic_updater]
autoware_auto_geometry: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
tier4_api_msgs: Cannot locate rosdep definition for [geographic_msgs]
grid_map_cv: Cannot locate rosdep definition for [filters]
trajectory_follower: Cannot locate rosdep definition for [diagnostic_updater]
tamagawa_imu_driver: Cannot locate rosdep definition for [can_msgs]
grid_map_ros: Cannot locate rosdep definition for [nav2_msgs]
obstacle_velocity_limiter: Cannot locate rosdep definition for [pcl_ros]
scenario_selector: Cannot locate rosdep definition for [topic_tools]
awapi_awiv_adapter: Cannot locate rosdep definition for [topic_tools]
image_diagnostics: Cannot locate rosdep definition for [diagnostic_updater]
velodyne_pointcloud: Cannot locate rosdep definition for [pcl_ros]
sample_vehicle_description: Cannot locate rosdep definition for [xacro]
pacmod_interface: Cannot locate rosdep definition for [diagnostic_updater]
radar_static_pointcloud_filter: Cannot locate rosdep definition for [radar_msgs]
external_cmd_selector: Cannot locate rosdep definition for [diagnostic_updater]
tier4_autoware_api_launch: Cannot locate rosdep definition for [topic_tools]
pointcloud_preprocessor: Cannot locate rosdep definition for [point_cloud_msg_wrapper]
radar_threshold_filter: Cannot locate rosdep definition for [radar_msgs]
localization_error_monitor: Cannot locate rosdep definition for [diagnostic_updater]
lanelet2_extension: Cannot locate rosdep definition for [lanelet2_validation]
probabilistic_occupancy_grid_map: Cannot locate rosdep definition for [pcl_ros]
tvm_utility: Cannot locate rosdep definition for [tvm_vendor]
ground_segmentation: Cannot locate rosdep definition for [pcl_ros]
autoware_point_types: Cannot locate rosdep definition for [point_cloud_msg_wrapper]
lidar_centerpoint_tvm: Cannot locate rosdep definition for [tvm_vendor]
behavior_path_planner: Cannot locate rosdep definition for [behaviortree_cpp_v3]
external_velocity_limit_selector: Cannot locate rosdep definition for [topic_tools]
lanelet2_map_preprocessor: Cannot locate rosdep definition for [pcl_ros]
tensorrt_common: Cannot locate rosdep definition for [tensorrt_cmake_module]
bluetooth_monitor: Cannot locate rosdep definition for [diagnostic_updater]
awsim_sensor_kit_launch: Cannot locate rosdep definition for [usb_cam]
autoware_testing: Cannot locate rosdep definition for [ros_testing]
map_loader: Cannot locate rosdep definition for [pcl_ros]
accel_brake_map_calibrator: Cannot locate rosdep definition for [diagnostic_updater]
osqp_interface: Cannot locate rosdep definition for [osqp_vendor]
system_monitor: Cannot locate rosdep definition for [diagnostic_updater]
tier4_localization_launch: Cannot locate rosdep definition for [topic_tools]
velodyne_driver: Cannot locate rosdep definition for [diagnostic_updater]
tensorrt_yolox: Cannot locate rosdep definition for [tensorrt_cmake_module]
grid_map_octomap: Cannot locate rosdep definition for [octomap]
velodyne_description: Cannot locate rosdep definition for [xacro]
grid_map_filters: Cannot locate rosdep definition for [filters]
tier4_vehicle_launch: Cannot locate rosdep definition for [xacro]
obstacle_stop_planner: Cannot locate rosdep definition for [pcl_ros]
external_cmd_converter: Cannot locate rosdep definition for [diagnostic_updater]
sample_sensor_kit_launch: Cannot locate rosdep definition for [usb_cam]
lidar_apollo_segmentation_tvm_nodes: Cannot locate rosdep definition for [ros_testing]
topic_state_monitor: Cannot locate rosdep definition for [diagnostic_updater]
lane_departure_checker: Cannot locate rosdep definition for [diagnostic_updater]
image_projection_based_fusion: Cannot locate rosdep definition for [pcl_ros]

I am installing autoware universe in ubuntu 20 in galactic version of ros. and facing this error, "rosdep update" doesnt help. Any solutions for this?

**Comment by Robotics010** [comment]
Have you sourced ros before using rosdep?
`source /opt/ros/galactic/setup.bash`

**Comment by Robotics010** [comment]
Also could try [this fix](https://github.com/Robotics010/carla_autoware_bridge/blob/master/troubleshooting.md#invalid-version-023ubuntu1-package-distro-info) ?

**Comment by prabanjanGITHUB** [comment]
Thanks for kindly replying. Now the 0.23 Ubuntu1 error is solved, but still rosdep error persist, I am sourcing the bash file.

pp@DESKTOP-TGAP0QJ:~/autoware$ rosdep install -y --from-paths src --ignore-src --rosdistro galactic
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
obstacle_collision_checker: Cannot locate rosdep definition for [pcl_ros]
velodyne_monitor: Cannot locate rosdep definition for [diagnostic_updater]
velodyne_pointcloud: Cannot locate rosdep definition for [pcl_ros]
lidar_centerpoint_tvm: Cannot locate rosdep definition for [tvm_vendor]
tier4_localization_launch: Cannot locate rosdep definition for [topic_tools]
lanelet2_extension: Cannot locate rosdep definition for [lanelet2_validation]
velodyne_driver: Cannot locate rosdep definition for [diagnostic_updater]
tensorrt_yolox: Cannot locate rosdep definition for [tensorrt_cmake_module]
sample_sensor_kit_launch: Cannot locate rosdep definition for [usb_cam]
external_cmd_converter: Cannot locate rosdep definition for [diagnostic_updater]
tensorrt_common: Cannot locate rosdep definition for [tensorrt_cmake_module]
radar_tracks_msgs_converter: Cannot locate rosdep definition for [radar_msgs]
web_controller: Cannot locate rosdep definition for [rosbridge_server]
autoware_point_types: Cannot locate rosdep definition for [point_cloud_msg_wrapper]
map_loader: Cannot locate rosdep definition for [pcl_ros]
system_error_monitor: Cannot locate rosdep definition for [rqt_robot_monitor]
front_vehicle_velocity_estimator: Cannot locate rosdep definition for [pcl_ros]
pacmod_interface: Cannot locate rosdep definition for [diagnostic_updater]
behavior_path_planner: Cannot locate rosdep definition for [behaviortree_cpp_v3]
external_velocity_limit_selector: Cannot locate rosdep definition for [topic_tools]
external_cmd_selector: Cannot locate rosdep definition for [diagnostic_updater]
image_projection_based_fusion: Cannot locate rosdep definition for [pcl_ros]
grid_map_cv: Cannot locate rosdep definition for [filters]
lidar_apollo_segmentation_tvm: Cannot locate rosdep definition for [tvm_vendor]
radar_static_pointcloud_filter: Cannot locate rosdep definition for [radar_msgs]
probabilistic_occupancy_grid_map: Cannot locate rosdep definition for [pcl_ros]
tier4_autoware_api_launch: Cannot locate rosdep definition for [topic_tools]
system_monitor: Cannot locate rosdep definition for [diagnostic_updater]
vehicle_cmd_gate: Cannot locate rosdep definition for [diagnostic_updater]
awapi_awiv_adapter: Cannot locate rosdep definition for [topic_tools]
topic_state_monitor: Cannot locate rosdep definition for [diagnostic_updater]
grid_map_octomap: Cannot locate rosdep definition for [octomap]
osqp_interface: Cannot locate rosdep definition for [osqp_vendor]
fault_injection: Cannot locate rosdep definition for [diagnostic_updater]
accel_brake_map_calibrator: Cannot locate rosdep definition for [diagnostic_updater]
awsim_sensor_kit_launch: Cannot locate rosdep definition for [usb_cam]
grid_map_ros: Cannot locate rosdep definition for [nav2_msgs]
tier4_vehicle_launch: Cannot locate rosdep definition for [xacro]
ground_segmentation: Cannot locate rosdep definition for [pcl_ros]
costmap_generator: Cannot locate rosdep definition for [pcl_ros]
velodyne_description: Cannot locate rosdep definition for [xacro]
lidar_apollo_segmentation_tvm_nodes: Cannot locate rosdep definition for [ros_testing]
planning_error_monitor: Cannot locate rosdep definition for [diagnostic_updater]
localization_error_monitor: Cannot locate rosdep definition for [diagnostic_updater]
scenario_selector: Cannot locate rosdep definition for [topic_tools]
trajectory_follower: Cannot locate rosdep definition for [diagnostic_updater]
tier4_api_msgs: Cannot locate rosdep definition for [geographic_msgs]
bluetooth_monitor: Cannot locate rosdep definition for [diagnostic_updater]
grid_map_demos: Cannot locate rosdep definition for [octomap_msgs]
obstacle_velocity_limiter: Cannot locate rosdep definition for [pcl_ros]
image_diagnostics: Cannot locate rosdep definition for [diagnostic_updater]
tvm_utility: Cannot locate rosdep definition for [tvm_vendor]
dummy_diag_publisher: Cannot locate rosdep definition for [diagnostic_updater]
autoware_auto_geometry: Cannot locate rosdep definition for [osrf_testing_tools_cpp]
trtexec_vendor: Cannot locate rosdep definition for [tensorrt_cmake_module]
pointcloud_preprocessor: Cannot locate rosdep definition for [point_cloud_msg_wrapper]
autoware_testing: Cannot locate rosdep definition for [ros_testing]
occupancy_grid_map_outlier_filter: Cannot locate rosdep definition for [pcl_ros]
radar_threshold_filter: Cannot locate rosdep definition for [radar_msgs]
lane_departure_checker: Cannot locate rosdep definition for [diagnostic_updater]
lanelet2_map_preprocessor: Cannot locate rosdep definition for [pcl_ros]
obstacle_stop_planner: Cannot locate rosdep definition for [pcl_ros]
tamagawa_imu_driver: Cannot locate rosdep definition for [can_msgs]
grid_map_costmap_2d: Cannot locate rosdep definition for [nav2_costmap_2d]
grid_map_filters: Cannot locate rosdep definition for [filters]
steer_offset_estimator: Cannot locate rosdep definition for [diagnostic_updater]
lidar_centerpoint: Cannot locate rosdep definition for [pcl_ros]
sample_vehicle_description: Cannot locate rosdep definition for [xacro]

**Comment by Robotics010** [comment]
Could you [try another fix](https://github.com/orgs/autowarefoundation/discussions/3168#discussioncomment-4554115)  then?

**Comment by prabanjanGITHUB** [comment]
Thanks a lot, That did resolve the issue. Great
