### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by prabanjanGITHUB** [Robotics010/carla_autoware_bridge#19]
pp@DESKTOP-TGAP0QJ:~/autoware$ colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
Starting >>> autoware_lint_common
Starting >>> autoware_auto_geometry_msgs
Starting >>> autoware_auto_mapping_msgs
Starting >>> tier4_debug_msgs
Starting >>> autoware_common_msgs
Starting >>> autoware_auto_system_msgs
Starting >>> tier4_planning_msgs
Starting >>> autoware_auto_control_msgs
Finished <<< autoware_lint_common [0.85s]
Starting >>> autoware_cmake
Finished <<< autoware_common_msgs [1.38s]
Finished <<< autoware_auto_geometry_msgs [1.51s]
Starting >>> autoware_planning_msgs
Starting >>> autoware_auto_perception_msgs
Finished <<< autoware_auto_control_msgs [1.70s]
Finished <<< autoware_auto_mapping_msgs [1.90s]
Starting >>> autoware_auto_planning_msgs
Starting >>> tier4_system_msgs
Finished <<< autoware_auto_system_msgs [1.99s]
Finished <<< tier4_debug_msgs [2.08s]
Starting >>> tier4_control_msgs
Starting >>> tier4_external_api_msgs
Finished <<< autoware_cmake [1.61s]
Starting >>> autoware_utils
Finished <<< tier4_planning_msgs [3.41s]
Starting >>> vehicle_info_util
Finished <<< autoware_utils [1.10s]
Starting >>> autoware_adapi_v1_msgs
Finished <<< autoware_planning_msgs [2.56s]
Starting >>> autoware_auto_common
Finished <<< tier4_control_msgs [2.45s]
Starting >>> tier4_vehicle_msgs
Finished <<< tier4_system_msgs [2.75s]
Starting >>> grid_map_cmake_helpers
Finished <<< vehicle_info_util [1.73s]
Starting >>> tier4_rtc_msgs
Finished <<< autoware_auto_perception_msgs [4.07s]
Starting >>> tier4_perception_msgs
Finished <<< autoware_auto_planning_msgs [3.94s]
Starting >>> autoware_auto_vehicle_msgs
Finished <<< autoware_auto_common [1.91s]
Starting >>> lanelet2_extension
Finished <<< grid_map_cmake_helpers [1.42s]
Starting >>> grid_map_core
Finished <<< autoware_adapi_v1_msgs [2.72s]
Starting >>> grid_map_msgs
Finished <<< tier4_rtc_msgs [2.03s]
Starting >>> autoware_auto_tf2
Finished <<< grid_map_core [1.22s]
Starting >>> grid_map_cv
Finished <<< tier4_external_api_msgs [5.76s]
Starting >>> component_interface_utils
Finished <<< tier4_vehicle_msgs [3.67s]
Starting >>> component_interface_specs
Finished <<< tier4_perception_msgs [2.79s]
Starting >>> autoware_point_types
Finished <<< grid_map_msgs [2.28s]
Starting >>> osqp_interface
Finished <<< grid_map_cv [1.60s]
Starting >>> grid_map_ros
Finished <<< autoware_point_types [1.46s]
Starting >>> tier4_pcl_extensions
Finished <<< osqp_interface [1.62s]
Starting >>> tier4_api_utils
Finished <<< component_interface_specs [2.21s]
Starting >>> tier4_localization_msgs
Finished <<< tier4_pcl_extensions [1.09s]
Finished <<< autoware_auto_tf2 [3.77s]
Starting >>> autoware_ad_api_specs
Finished <<< component_interface_utils [3.19s]
Starting >>> tier4_api_msgs
Starting >>> tier4_v2x_msgs
Finished <<< autoware_auto_vehicle_msgs [5.33s]
Finished <<< lanelet2_extension [5.22s]
Starting >>> tier4_autoware_utils
Starting >>> tier4_auto_msgs_converter
Finished <<< grid_map_ros [2.71s]
Starting >>> autoware_auto_geometry
Finished <<< autoware_ad_api_specs [0.94s]
Starting >>> velodyne_msgs
Finished <<< tier4_localization_msgs [1.68s]
Starting >>> signal_processing
Finished <<< tier4_api_utils [2.08s]
Starting >>> grid_map_pcl
Finished <<< tier4_v2x_msgs [1.93s]
Starting >>> rtc_interface
Finished <<< signal_processing [1.36s]
Starting >>> kalman_filter
Finished <<< velodyne_msgs [1.74s]
Starting >>> autoware_map_msgs
Finished <<< kalman_filter [0.88s]
Starting >>> mussp
Finished <<< rtc_interface [1.46s]
Finished <<< tier4_api_msgs [3.57s]
Starting >>> velodyne_driver
Starting >>> velodyne_monitor
Finished <<< grid_map_pcl [2.72s]
Starting >>> global_parameter_loader
Finished <<< mussp [1.07s]
Starting >>> velodyne_pointcloud
Finished <<< autoware_map_msgs [1.96s]
Starting >>> autoware_sensing_msgs
Finished <<< tier4_autoware_utils [4.59s]
Starting >>> interpolation
Finished <<< velodyne_monitor [1.41s]
Starting >>> pointcloud_preprocessor
Finished <<< velodyne_driver [1.71s]
Starting >>> grid_map_utils
Finished <<< autoware_auto_geometry [4.93s]
Starting >>> ndt_omp
Finished <<< global_parameter_loader [1.84s]
Starting >>> pointcloud_to_laserscan
Finished <<< autoware_sensing_msgs [1.56s]
Starting >>> tier4_simulation_msgs
Finished <<< ndt_omp [0.72s]
Starting >>> geo_pos_conv
Finished <<< pointcloud_to_laserscan [0.83s]
Starting >>> tvm_utility
Finished <<< tier4_auto_msgs_converter [6.72s]
Starting >>> dummy_perception_publisher
Finished <<< geo_pos_conv [1.04s]
Starting >>> external_cmd_selector
Finished <<< tier4_simulation_msgs [1.49s]
Starting >>> freespace_planning_algorithms
Finished <<< tvm_utility [1.25s]
Starting >>> map_loader
Finished <<< velodyne_pointcloud [4.02s]
Starting >>> shape_estimation
Finished <<< interpolation [4.28s]
Starting >>> motion_utils
Finished <<< grid_map_utils [4.44s]
Starting >>> perception_utils
Finished <<< pointcloud_preprocessor [6.64s]
Starting >>> compare_map_segmentation
Finished <<< dummy_perception_publisher [5.13s]
Starting >>> raw_vehicle_cmd_converter
Finished <<< freespace_planning_algorithms [4.62s]
Starting >>> autoware_adapi_version_msgs
Finished <<< shape_estimation [4.98s]
Starting >>> tamagawa_imu_driver
Finished <<< autoware_adapi_version_msgs [1.44s]
Starting >>> velodyne_description
Finished <<< tamagawa_imu_driver [0.61s]
Starting >>> autoware_external_api_msgs
Finished <<< motion_utils [5.24s]
Starting >>> route_handler
Finished <<< velodyne_description [0.78s]
Starting >>> lane_departure_checker
Finished <<< perception_utils [5.28s]
Starting >>> trajectory_follower
Finished <<< map_loader [7.54s]
Starting >>> lidar_centerpoint
Finished <<< external_cmd_selector [8.26s]
Starting >>> motion_velocity_smoother
Finished <<< autoware_external_api_msgs [2.36s]
Starting >>> obstacle_avoidance_planner
Finished <<< raw_vehicle_cmd_converter [6.85s]
Starting >>> component_state_monitor
Finished <<< route_handler [8.77s]
Starting >>> mission_planner
Finished <<< component_state_monitor [4.47s]
Starting >>> external_velocity_limit_selector
Finished <<< lane_departure_checker [10.9s]
Starting >>> behavior_path_planner
Finished <<< motion_velocity_smoother [10.3s]
Starting >>> grid_map_octomap
Finished <<< obstacle_avoidance_planner [11.0s]
Starting >>> gyro_odometer
Finished <<< trajectory_follower [12.6s]
Starting >>> pure_pursuit
Finished <<< external_velocity_limit_selector [6.28s]
Starting >>> image_transport_decompressor
Finished <<< grid_map_octomap [3.92s]
Starting >>> object_range_splitter
Finished <<< gyro_odometer [4.68s]
Starting >>> rtc_auto_mode_manager
Finished <<< image_transport_decompressor [4.64s]
Starting >>> traffic_light_classifier
Finished <<< object_range_splitter [4.79s]
Starting >>> traffic_light_ssd_fine_detector
Finished <<< rtc_auto_mode_manager [2.76s]
Starting >>> automatic_pose_initializer
Finished <<< traffic_light_classifier [4.06s]
Starting >>> detected_object_feature_remover
Finished <<< traffic_light_ssd_fine_detector [5.38s]
Starting >>> emergency_handler
Finished <<< automatic_pose_initializer [5.38s]
Starting >>> gnss_poser
Finished <<< pure_pursuit [13.2s]
Starting >>> shift_decider
Finished <<< mission_planner [18.0s]
Starting >>> tensorrt_yolo
Finished <<< detected_object_feature_remover [4.13s]
Starting >>> vehicle_cmd_gate
Finished <<< gnss_poser [5.12s]
Starting >>> common_sensor_launch
Finished <<< shift_decider [19.5s]
Starting >>> costmap_generator
Finished <<< emergency_handler [24.4s]
Starting >>> crosswalk_traffic_light_estimator
Finished <<< common_sensor_launch [20.8s]
Starting >>> ekf_localizer
[Processing: behavior_path_planner, compare_map_segmentation, costmap_generator, crosswalk_traffic_light_estimator, ekf_localizer, lidar_centerpoint, tensorrt_yolo, vehicle_cmd_gate]
[Processing: behavior_path_planner, compare_map_segmentation, costmap_generator, crosswalk_traffic_light_estimator, ekf_localizer, lidar_centerpoint, tensorrt_yolo, vehicle_cmd_gate]nsorrt_yolo:cmake - 1min 16.9s] ...
[Processing: behavior_path_planner, compare_map_segmentation, costmap_generator, crosswalk_traffic_light_estimator, ekf_localizer, lidar_centerpoint, tensorrt_yolo, vehicle_cmd_gate]
[Processing: behavior_path_planner, compare_map_segmentation, costmap_generator, crosswalk_traffic_light_estimator, ekf_localizer, lidar_centerpoint, tensorrt_yolo, vehicle_cmd_gate]nsorrt_yolo:build - 2min 35.8s] ...
[Processing: behavior_path_planner, compare_map_segmentation, costmap_generator, crosswalk_traffic_light_estimator, ekf_localizer, lidar_centerpoint, tensorrt_yolo, vehicle_cmd_gate]
--- stderr: compare_map_segmentation
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/compare_map_segmentation.dir/build.make:89: CMakeFiles/compare_map_segmentation.dir/src/voxel_based_compare_map_filter_nodelet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/compare_map_segmentation.dir/build.make:115: CMakeFiles/compare_map_segmentation.dir/src/compare_elevation_map_filter_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/compare_map_segmentation.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< compare_map_segmentation [3min 42s, exited with code 2]
Aborted  <<< lidar_centerpoint [3min 38s]
Aborted  <<< costmap_generator [3min 6s]
Aborted  <<< tensorrt_yolo [4min 20s]
Aborted  <<< crosswalk_traffic_light_estimator [4min 15s]
Aborted  <<< behavior_path_planner [5min 1s]
Aborted  <<< ekf_localizer [4min 30s]
Aborted  <<< vehicle_cmd_gate [5min 22s]

Summary: 97 packages finished [6min 17s]
  1 package failed: compare_map_segmentation
  7 packages aborted: behavior_path_planner costmap_generator crosswalk_traffic_light_estimator ekf_localizer lidar_centerpoint tensorrt_yolo vehicle_cmd_gate
  2 packages had stderr output: behavior_path_planner com

During the final step of autoware installation some packages are aborted and failing. I have enough space in my disk. Faced the same issue before?

**Comment by Robotics010** [comment]
No, I haven't seen the same issue before, but I can not see any error description here. So it looks like something system-related rather than package-related.
Do you have enough RAM? I didn't see RAM minimum recomendation, but I would say if you don't have 32 GB RAM available, then add a swap memory.
Also you can compile with colcon in sequence rather than in parallel. It will be longer, but it won't overflow your RAM.

**Comment by prabanjanGITHUB** [comment]
I was keep on repeating the Colcon build command. Every time the build process was failing in a new package.  like first time it failed at 130th package, next time it failed in 190th package, finally after repeating Colcon build for serval times, build is successful.
