### ISSUE TITLE
Vehicle Visualization Error

### ISSUE THREAD

**Issue by prabanjanGITHUB** [Robotics010/carla_autoware_bridge#20]
<img width="960" alt="No vehicle autoware  universe WSL" src="https://github.com/Robotics010/carla_autoware_bridge/assets/135314752/1a53b76b-be42-4011-a2ac-e1b957247db8">
![no vehicle terminal output](https://github.com/Robotics010/carla_autoware_bridge/assets/135314752/ab7b6686-9ca6-4d72-b59b-8084143a61a5)

I understand this is not issue related to this repo. still wondering have you faced this bug before! I am using autoware universe galactic. when I give a Initial pose estimate, the vehicle graphics is not showing up. even when engaging the vehicle after giving a goal pose, the planner starts working, still without the vehicle graphics. I attached the terminal output as well. Should I toggle any options? 

Thanks.

**Comment by Robotics010** [comment]
I haven't faced with the same problem. When I was trying autoware planning simulator tutorial the vehicle model was shown properly. I suggest you try find help with the problem in autoware discussions.
