### ISSUE TITLE
Error: easy_install command is deprecated 

### ISSUE THREAD

**Issue by prabanjanGITHUB** [Robotics010/carla_autoware_bridge#21]
--- stderr: carla_tesla_model3_description
/home/pp/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/pp/.local/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---

while building the packages after adding the given additional repos in autoware. There are several instances of this warning message. Can it be ignored? How can I resolve this! Please.

**Comment by Robotics010** [comment]
Good news are that you can ingnore that warning. It just saying that when we are going to use more recent version of installing python packages tool, than we will be required to use more suited tool for that.
Unfortunately it is ros2 wide related issue (https://github.com/colcon/colcon-core/issues/454), so I would just be waiting for a corresponding solution from the recent ros2 version.
