### ISSUE TITLE
Package "Trajectory Follower" installation go wrong

### ISSUE THREAD

**Issue by eromreve123** [Robotics010/carla_autoware_bridge#24]
I`ve been stucked at this problem for days, and need some help!
Before "Trajectory Follower" installation fails. threre are more than 50 package that have been successfully installed.
Here is the detail after I run "colcon build":

--- stderr: trajectory_follower          
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_bounds'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_alpha'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_polish'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_lower_bound'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_warm_start_x'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_warm_start_y'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_polish_refine_iter'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_eps_abs'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_upper_bound'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_A'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_check_termination'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_verbose'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `csc_matrix'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_lin_cost'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_P'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_eps_rel'
/usr/bin/ld: /home/qyc/autoware/install/osqp_interface/lib/libosqp_interface.so: undefined reference to `osqp_update_max_iter'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_lateral_controller.dir/build.make:391: test_lateral_controller] Error 1
make[1]: *** [CMakeFiles/Makefile2:215: CMakeFiles/test_lateral_controller.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< trajectory_follower [1.64s, exited with code 2]

**Comment by Robotics010** [comment]
Hey @eromreve123 could you describe your case more in detail? Like what OS do you use (is it Ubuntu 20.04?)? What installation steps did you perform? What troubleshooting steps have you tried so far?
